LITHO,CANAL,R
006303,B,C,D,A,E,C,C,C,E,D,D,C,E,B,B,D,B,C,C,B,D,D,C,A,C,E,D,C,E,B,E,D,E,B,B,B,A,B,C,A,D,C,B,B,A,C,B,E,D,A,B,B,D,C,B,C,B,B,D,B,D,D,A,D,B,C,A,E,A,E,E,B,C,C,C,C,C,C,C,D,B,C,D,D,E,A,B,A,D,A,A,C,E,E,C,B,B,C,A,A,A
