LITHO,CANAL,R
002640,C,A,D,E,A,D,D,B,B,E,B,D,B,C,A,C,C,C,A,C,A,C,A,B,B,C,A,B,D,A,A,D,C,C,D,A,E,B,A,B,C,C,B,C,B,C,D,D,A,A,C,D,E,E,C,E,A,A,B,C,A,B,C,D,D,C,B,C,A,C,E,D,A,B,D,A,D,E,C,C,E,B,A,E,C,A,A,B,A,D,A,B,C,C,E,C,B,E,C,D,C
