LITHO,CANAL,R
002328,A,B,A,D,A,A,E,D,D,D,A,C,A,E,B,B,D,C,E,D,C,D,D,D,C,A,D,B,D,B,A,E,B,E,C,E,E,D,A,E,E,D,E,B,C,E,A,A,C,A,B,D,C,B,A,D,B,C,A,B,E,A,D,E,B,E,D,E,C,C,A,D,C,B,B,C,A,A,C,A,D,B,C,D,A,D,D,E,B,B,B,A,D,C,A,C,C,A,D,B,C
