LITHO,CANAL,R
004989,A,E,A,D,D,B,D,A,E,B,C,D,B,C,B,B,C,C,D,B,A,D,C,D,D,D,E,E,D,C,D,E,A,B,A,C,B,E,B,E,C,C,E,D,C,D,D,C,C,B,C,C,C,D,C,C,A,C,D,B,D,A,B,D,A,B,C,B,A,A,D,E,C,C,A,C,A,D,D,A,C,B,C,A,C,B,E,C,B,D,E,A,A,B,A,B,D,A,E,A,C
