LITHO,CANAL,R
004990,B,E,A,D,D,B,D,A,E,B,C,D,B,C,B,B,C,C,D,B,A,D,C,D,D,D,E,E,D,C,D,E,A,B,A,C,B,E,B,E,C,C,E,D,C,D,D,C,C,B,C,A,E,C,B,E,A,A,B,D,E,A,A,E,A,A,A,C,C,A,C,B,C,D,B,D,B,B,C,A,E,A,C,B,A,C,C,A,E,A,D,A,D,C,A,B,D,D,C,D,C
