LITHO,CANAL,R
004971,A,B,B,D,D,C,B,B,D,C,E,C,B,A,C,D,C,D,C,B,E,A,D,C,E,C,C,C,E,D,E,D,B,E,D,D,E,E,B,E,A,D,D,B,B,D,D,B,C,B,C,A,C,B,D,D,C,B,A,E,C,D,B,C,B,B,A,E,D,E,B,E,C,A,A,A,D,C,C,D,C,D,C,A,E,B,E,B,A,E,A,D,A,A,B,B,C,E,D,E,B
004972,A,B,D,D,E,C,B,D,A,C,E,B,D,A,C,B,D,,B,B,E,C,A,D,B,A,D,B,D,C,B,A,A,D,A,D,C,B,E,D,B,C,B,D,C,A,D,B,,*,C,B,D,A,C,E,B,E,B,D,A,C,D,D,B,E,C,A,D,B,E,B,E,A,C,C,D,C,E,C,A,B,A,A,E,B,E,D,C,A,E,C,A,D,B,D,C,A,D,C,E
