LITHO,CANAL,R
000523,D,C,B,A,C,E,E,A,B,A,B,A,C,B,A,B,A,C,B,D,C,C,E,A,E,D,A,C,E,E,A,B,C,E,D,B,D,B,D,B,C,C,D,B,D,A,B,D,D,C,B,C,D,D,C,C,A,A,C,D,D,B,D,E,D,C,D,E,C,A,A,B,C,E,E,B,B,B,A,D,B,B,B,E,D,C,A,A,B,A,B,A,C,E,A,D,B,D,B,C,B
