LITHO,CANAL,R
003500,D,A,B,E,C,D,D,E,A,E,A,D,C,C,C,D,E,B,D,B,D,D,A,C,A,B,E,B,E,C,A,D,C,A,E,A,D,C,D,C,C,D,B,E,A,D,B,E,D,D,B,C,D,C,E,B,C,A,A,C,D,B,C,B,D,C,E,A,C,A,C,D,E,B,D,B,C,B,B,D,D,D,D,C,B,D,A,E,B,E,C,E,B,D,D,E,E,E,A,E,C
