LITHO,CANAL,R
001086,D,B,B,,B,C,E,B,D,D,D,A,C,A,B,B,E,C,B,C,C,A,B,D,B,D,D,C,E,E,A,B,C,E,E,B,D,D,C,D,C,B,C,B,D,A,C,D,E,C,B,C,D,B,C,B,E,A,B,D,D,B,E,D,E,A,E,B,D,E,E,B,C,E,E,D,A,D,B,D,B,B,C,D,E,C,C,A,B,C,D,E,D,D,D,C,C,D,B,A,C
