LITHO,CANAL,R
005805,B,B,B,E,B,D,B,B,C,C,A,D,D,B,B,E,E,D,B,E,C,B,B,D,E,C,A,B,D,A,A,B,A,B,E,B,C,C,A,E,B,E,C,B,C,A,E,E,A,D,B,D,C,A,B,A,E,A,D,D,D,C,A,E,A,D,A,C,E,D,A,B,E,D,E,A,C,C,A,E,D,D,A,C,B,D,C,A,B,B,B,B,D,A,C,A,C,C,D,A,A
