LITHO,CANAL,R
005969,A,B,B,E,B,D,B,B,C,C,A,D,D,B,B,E,E,D,B,E,C,B,B,D,E,C,A,B,D,A,A,B,A,B,E,B,C,C,A,E,B,E,C,B,C,A,E,E,A,D,B,C,B,A,B,E,A,B,A,B,C,C,D,B,D,C,D,C,C,C,C,E,B,E,D,B,C,C,E,D,B,A,B,B,D,B,E,A,D,B,D,C,B,B,E,A,D,A,C,E,C
