LITHO,CANAL,R
000375,C,C,C,A,C,E,B,B,D,D,B,D,D,B,C,D,D,E,D,C,C,E,B,C,B,C,E,B,E,A,C,D,A,C,C,C,B,B,B,A,C,D,D,C,A,E,D,A,A,E,D,A,A,E,D,B,C,D,B,D,D,A,A,D,D,B,E,C,A,A,A,E,B,C,B,C,E,A,B,C,A,B,C,E,B,D,A,D,E,A,D,B,B,E,C,A,D,D,C,A,B
