LITHO,CANAL,R
000184,A,C,E,B,A,C,D,B,C,D,B,A,A,B,B,A,E,B,B,A,C,B,E,C,C,D,E,A,E,A,E,A,E,A,B,B,D,C,D,C,B,C,D,D,B,B,D,D,E,B,D,D,A,B,E,A,C,A,A,C,D,A,E,A,B,C,B,D,C,C,C,D,B,C,D,E,D,C,A,B,C,E,E,B,A,D,B,A,D,E,B,A,B,D,D,D,B,A,E,C,E
