LITHO,CANAL,R
001430,C,C,E,C,B,A,D,A,C,D,D,B,C,D,E,C,E,B,A,D,C,A,E,C,D,B,E,D,E,B,C,A,D,C,A,C,E,D,E,B,D,C,B,A,E,D,D,B,A,D,D,D,C,C,E,D,E,B,D,D,B,B,C,C,D,D,E,D,B,A,E,D,B,D,E,C,D,E,B,C,B,B,C,A,C,C,B,C,C,E,C,C,D,D,B,D,A,C,E,B,B
