LITHO,CANAL,R
005093,B,D,B,A,D,D,C,E,C,A,D,A,B,E,C,C,C,C,A,D,D,B,B,C,E,D,E,D,D,E,C,E,E,B,B,E,E,C,D,E,C,E,C,C,A,A,B,E,E,C,C,A,D,B,A,D,D,C,E,C,C,C,A,C,B,E,E,A,C,B,C,A,D,D,E,A,C,B,C,E,D,A,D,C,B,E,C,C,A,D,D,D,C,B,C,C,D,D,A,B,B
