LITHO,CANAL,R
005092,A,D,B,A,D,D,C,E,C,A,D,A,B,E,C,C,C,C,A,D,D,B,B,C,E,D,E,D,D,E,C,E,E,B,B,E,E,C,D,E,C,E,C,C,A,A,B,E,E,C,C,B,A,B,E,B,B,C,C,D,A,A,D,C,A,C,B,A,A,D,D,C,D,C,A,E,A,B,B,D,C,C,D,D,D,B,B,A,B,D,C,D,E,C,D,C,A,C,A,C,D
