LITHO,CANAL,R
002994,C,A,B,C,B,E,D,D,E,E,B,B,B,E,E,D,B,C,B,B,D,D,B,B,B,B,C,A,B,A,A,C,C,C,B,B,B,A,C,B,C,C,E,C,A,D,A,B,D,B,A,C,D,D,C,A,C,C,A,B,E,B,C,B,A,B,B,E,C,A,A,D,D,C,C,A,A,D,E,E,C,B,C,D,C,D,E,C,C,A,E,B,A,E,C,B,A,B,E,C,C
